### ISSUE TITLE
new peoblem!

### ISSUE THREAD

**Issue by iceees** [Vosloo/Collision-avoidance#1]
can't pip install roboticstoolbox_python.egg==0.6.2
ERROR: Could not find a version that satisfies the requirement roboticstoolbox_python.egg==0.6.2 (from versions: none)
ERROR: No matching distribution found for roboticstoolbox_python.egg==0.6.2

so I install roboticstoolbox_python ,but from roboticstoolbox.robot.Shape import Sphere and from roboticstoolbox.backends.Swift.Swift import Swift is error 

what should  I do to solve this problem

**Comment by Vosloo** [comment]
Hello there! Unfortunately, I did this a long time ago, and I do not remember the details. I was working on this more than two years ago, so I guess a lot has changed since then. I think your best bet would be to visit https://github.com/petercorke/robotics-toolbox-python and install the robotics toolbox version directly from the instructions in the README.

At this point, I do not even remember the Python version I was using, but I suspect it might have been 3.6 or 3.7. You can try to install the version I was using with `pip3 install roboticstoolbox-python==0.6.2`, although it seems to be a really old version of the library. Anyway, I wish you luck in finding the solution to the issue, as I cannot help you with that.
